### ISSUE TITLE
Error: kss expected the builder to implement KssBuilderBase API version 3.0; version "3.0" is being used instead.

### ISSUE THREAD

**Issue by ryuran** [kss-node/kss-node#389]
> Error: kss expected the builder to implement KssBuilderBase API version 3.0; version "3.0" is being used instead.

I try to use a custom builder with a relative path.
- Maybe it's a bad path and KSS do not find the builder but the error message is not helping.
- Or it's because my kssBuilder is in an other project and not require the same base than my current KSS. Same version but do not valid `intanceOf`

**Comment by RobLoach** [comment]
You may need to update the KSS custom builder to the latest version of KSS. Have the source available on github?

**Comment by ryuran** [comment]
I find my problem.

My kss builder require kssBuilderBase of an other install of kss.
So there is not intanceOf KssBuilderBase even if it's the same version.

I fixed it using the same instance of kss than my kssBuilder.

**Comment by MartinMuzatko** [comment]
I also have the same problem. just cloned a fresh copy and the cli throws this error at me. I do not have any other installation of KSS on the system.

**Comment by MartinMuzatko** [comment]
Removing the builder.js file solves the problem for me. However, KSS should throw a proper error when this happens. I still don't really understand what the cause of the problem is. and why 3.0 is not 3.0.
